version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: axbot_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nyambalo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    container_name: api
    restart: always
    build: .
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
volumes:
  mongo_data:
